version: '3.7'

services:
  devcontainer:
    image: acme/orderservice-prod-container:0.1
    build:
      context: ..
      dockerfile: ./infra/Dockerfile.prod
    container_name: orderservice-prod-container
    hostname: orderservice-prod.local
    working_dir: /src
    ports:
       - 4000:3001 # express serves at 3001
    volumes:
       - ..:/src
       # Allow AWS CLI and other tools to read an AWS profile
       - ~/.aws:/home/node/.aws
    environment:
       - REACT_APP_HELLO=https://prod.example.com/1556hrs
    command: sleep infinity
